[loggers]
keys = root,app.extractor,app.transformer,app.loader

[handlers]
keys = fileHandler

[formatters]

keys = fileFormatter

[logger_root]

level = DEBUG
handlers = fileHandler

[logger_app.extractor]
level = DEBUG
handlers = fileHandler
qualname = app.extractor
propagate = 0

[logger_app.transformer]
level = DEBUG
handlers = fileHandler
qualname = app.transformer
propagate = 0

[logger_app.loader]
level = DEBUG
handlers = fileHandler
qualname = app.loader
propagate = 0

[handler_fileHandler]
class = FileHandler
level = DEBUG
formatter = fileFormatter
args = ('logs/bin_crypto_pipeline.log','a')

[formatter_fileFormatter]
format = %(asctime)s - %(name)s - %(levelname)s - %(message)s
datefmt = %d-%b-%y %H:%M:%S